#### Practice Dry Code Exercise

* **Author:** Mark Brown
* **Date:** 31/12/18

#### Import Python Packages

In the questions below, you will be working with numpy arrays and pandas dataframes.

You will also be downloading files using urllib.request and accessing directories and files on your computer using os. Last, you will also be creating plots of your data.

Import all of the necessary Python packages to accomplish these tasks.

In [2]:
# import necessary packages
import os
import numpy as np
import pandas as pd
import urllib.request
import matplotlib.pyplot as plt

print("All packages successfully imported")

All packages successfully imported


#### Get Data
#### Numpy Arrays

Use .urllib.request to download the following .csv files of monthly precipitation (inches) and import the data to numpy arrays:

1. monthly-precip-1988-to-1992.csv from https://ndownloader.figshare.com/files/12807380

2. monthly-precip-1993-to-1997.csv from https://ndownloader.figshare.com/files/12807383

Each dataset contains a row for each year specified in the dataset name and contains a column for each month (starting with January through December).

In [3]:
# set the working directory
os.chdir("/Users/markb/earth-analytics-bootcamp/")

# download monthly-precip-1988-to-1992.csv
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807380",
                          filename = "data/monthly-precip-1988-to-1992.csv")

# download monthly-precip-1993-to-1997.csv
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807383", 
                          filename = "data/monthly-precip-1993-to-1997.csv")

# print message that files were downloaded successfully
print("Datasets sucessfully downloaded")

Datasets sucessfully downloaded


In [4]:
# import the downloaded files into new numpy arrays
precip_88_to_92 = np.loadtxt(fname = "/Users/markb/earth-analytics-bootcamp/data/monthly-precip-1988-to-1992.csv", delimiter = ",")

precip_93_to_97 = np.loadtxt(fname = "/Users/markb/earth-analytics-bootcamp/data/monthly-precip-1993-to-1997.csv", delimiter = ",")

# print message to show that files sucessfully created
print("Numpy arrays sucessfully created")

# display values in numpy array as floats rather than scientific
# notation
np.set_printoptions(suppress=True)

# print the newly created numpy arrays
print(precip_88_to_92)
print(precip_93_to_97)

Numpy arrays sucessfully created
[[0.4  1.14 2.53 1.48 3.7  0.7  0.71 1.33 2.02 0.03 0.75 2.16]
 [1.19 1.27 0.97 1.95 2.68 2.93 1.43 1.63 3.54 1.4  0.09 1.54]
 [1.04 1.32 4.55 2.16 1.73 0.39 4.23 1.13 1.84 0.96 1.6  0.75]
 [1.05 0.15 0.43 2.41 2.9  3.59 3.11 2.08 1.21 0.93 3.3  0.01]
 [0.67 0.   5.17 0.46 1.7  0.96 1.13 3.08 0.02 0.79 2.56 0.84]]
[[0.25 0.9  2.15 2.56 1.73 3.38 1.4  1.04 3.32 2.42 2.17 0.55]
 [0.86 1.37 1.61 3.46 1.35 0.93 0.35 2.56 0.54 1.02 2.25 0.49]
 [0.64 1.53 1.21 5.45 9.59 4.03 0.72 1.45 2.96 0.59 1.51 0.25]
 [1.89 0.29 2.16 1.49 4.63 2.77 1.96 0.63 3.48 0.28 1.43 0.37]
 [0.87 1.83 0.91 5.77 2.19 3.69 1.14 5.27 1.92 2.7  1.52 0.68]]


#### Pandas Dataframes

Use .urllib.request to download the following .csv files of monthly temperature (Fahrenheit) and import the data to pandas dataframes:

1. temp-1991-to-1995-months.csv from https://ndownloader.figshare.com/files/12807389

2. temp-1996-to-2000-months.csv from https://ndownloader.figshare.com/files/12807386

Each dataset contains a row for each year specified in the dataset name and a column for each month (starting with January through December).

Note: you are not required to write a loop to accomplish these tasks. You can follow the same process that you have before to download and import files.

In [7]:
# download temp-1991-to-1995-months.csv
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807389",
                          filename = "data/temp-1991-to-1995-months.csv")

# download temp-1996-to-2000-months.csv
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807386",
                          filename = "data/temp-1996-to-2000-months.csv")

# print message to show have files have downloaded
print("Files successfully downloaded")

# import the downloaded files as a pandas dataframe
temp_91_95_months = pd.read_csv("/Users/markb/earth-analytics-bootcamp/data/temp-1991-to-1995-months.csv")

temp_96_00_months = pd.read_csv("/Users/markb/earth-analytics-bootcamp/data/temp-1996-to-2000-months.csv")

# print the pandas dataframe
temp_91_95_months



Files successfully downloaded


Year  January  February  March  April   May  June  July  August  September  \
0  1991     29.9      40.9   42.8   47.8  58.2  66.6  70.5    69.2       61.7   
1  1992     35.9      40.6   43.3   54.3  59.1  62.9  68.3    66.3       64.4   
2  1993     28.3      30.6   42.4   47.6  57.5  64.5  69.5    67.3       58.8   
3  1994     35.5      31.9   43.9   47.6  60.8  70.0  71.2    70.9       65.0   
4  1995     34.5      38.3   42.1   45.1  50.9  62.4  70.5    74.0       60.4   

   October  November  December  
0     52.1      36.8      35.3  
1     54.1      34.1      29.2  
2     48.7      35.6      35.4  
3     50.6      36.6      36.1  
4     50.5      45.0      36.3

In [6]:
# print the pandas dataframe
temp_96_00_months

Year  January  February  March  April   May  June  July  August  September  \
0  1996     29.7      37.7   37.9   50.4  58.9  66.9  71.5    69.5       60.8   
1  1997     31.3      32.8   45.5   42.8  57.4  66.5  71.4    68.7       64.0   
2  1998     36.5      36.4   38.7   46.5  58.8  62.1  72.8    70.7       67.1   
3  1999     36.4      42.1   46.0   44.5  55.6  64.8  73.5    69.3       58.5   
4  2000     36.4      41.0   42.9   51.2  61.0  67.4  74.7    73.0       63.1   

   October  November  December  
0     53.1      40.6      36.5  
1     52.7      37.9      33.9  
2     50.4      44.0      32.2  
3     51.9      48.0      36.9  
4     49.6      31.4      31.2

#### Question 1: Use Indexing to Select from Numpy Array

Select the second row of data (including all columns) from the numpy array containing the data for 1988 to 1992, and save to a new numpy array.

Note that using an index series (e.g. [row_index:row_index, column_index:column_index]) to select the rows and columns will result in a two-dimensional array.

Name your new array appropriately to indicate the year of data that it represents.

In [26]:
# select second row of data from 'precip_88_to_92' and save to a 
# new array called 

precip_89 = precip_88_to_92[1:2, : ]

# print new array
precip_89

array([[1.19, 1.27, 0.97, 1.95, 2.68, 2.93, 1.43, 1.63, 3.54, 1.4 , 0.09,
        1.54]])

#### Question 2: Write a Conditional Statement to Check Dimensions of Numpy Array

Write a conditional statement that checks whether the numpy array created in the previous question (i.e. the selection) is a one-dimensional numpy array.

Print a message stating whether or not the array is one-dimensional.

Hints:

    It is easier to write this conditional statement using the attribute of numpy arrays that provides a single value for the dimension (i.e. .ndim), rather than the shape.
    Recall how to use the comparison operator to check for equality between values (==).

In [27]:
# check to see if precip_89 is a one dimensional array

if precip_89.ndim == 1:
    print("This is a one-dimensional array")
else:
    print("This is NOT a one-dimensional array")

This is NOT a one-dimensional array


#### Question 3: Expand Conditional Statement to Execute Different Code

Modify your conditional statement from the previous question, so that your if and else statements execute different code, not just printing messages.

For the if statement, rather than printing a message, print the shape of the numpy array from the previous question (i.e. the selection).

For the else statement, rather than printing a message, include the following code lines to be executed (i.e. if the array is not one-dimensional):

* arrayname_1d = arrayname.flatten()
* print(arrayname_1d.shape)

These code lines will flatten a numpy array (in this case named arrayname) to a one-dimensional array, save it to a new array called arrayname_1d, and print the shape of the new array.

Note the result of this conditional statement.

In [29]:
# while loop to carry out instructions outlined above 

if precip_89.ndim == 1:
    # print shape of numpy array
    precip_89.shape
    
else:
    # flatten numpy array then print new array
    precip_89_1d = precip_89.flatten()
    print(precip_89_1d.shape)

(12,)


#### Question 4: Write a Conditional Statement to Check Dimensions of Two Numpy Arrays

Manually create a one-dimensional numpy array that contains the month names (i.e. January to December).

Write a conditional statement to check that this new array for month names has the same shape as the numpy array from the previous question (i.e. the selection).

Print a message stating whether are not these arrays have the same shape and can be plotted together.

Hints:

* Review the Activity on Data Structures from Day 6 if you need to recall how to manually create a numpy array using np.array([]).
* Note that you are creating this new array using text strings, not numeric values.
* Recall how to use the comparison operator to check for equality between values (==).

In [32]:
# create new numpy array of month names
months = np.array(["Jan", 
                  "Feb", 
                   "Mar", 
                  "Apr", 
                  "May", 
                  "Jun", 
                  "Jul", 
                  "Aug", 
                  "Sept", 
                  "Oct",
                  "Nov", 
                  "Dec"])

# write conditional statement to check if new 'months' array has
# the same shape as the new numpy array in previous question

if months.shape == precip_89_1d.shape:
    print("The arrays have the same shape and can be plotted together")

else:
    print("The arrays have different shapes and therefore cant be plotted")

The arrays have the same shape and can be plotted together


#### Question 5: Practice Pseudo Coding

Reflect on your conditional statement from the previous question.

Write a sentence or two on how you could expand on your conditional statement from the previous question to create a plot from the two numpy arrays if they do indeed have the same shape.

Hint: what did you do in Question 3 to expand on your conditional statement?

In order for a plot to be created from two numpy arrays the plots need to be of the same dimensions.

To build this into the conditional statement in Question 4 I would add code to create a plot if the conditional statement is true, i.e. the shapes of the two numpy arrays are the same.

I would leave the else statement the same to print a statement that the arrays have different shapes and therefore a plot could not be created.