#### Practice Dry Code Exercise

* **Author:** Mark Brown
* **Date:** 31/12/18

#### Import Python Packages

In the questions below, you will be working with numpy arrays and pandas dataframes.

You will also be downloading files using urllib.request and accessing directories and files on your computer using os. Last, you will also be creating plots of your data.

Import all of the necessary Python packages to accomplish these tasks.

In [1]:
# import necessary packages
import os
import numpy as np
import pandas as pd
import urllib.request
import matplotlib.pyplot as plt

print("All packages successfully imported")

All packages successfully imported


#### Get Data
#### Numpy Arrays

Use .urllib.request to download the following .csv files of monthly precipitation (inches) and import the data to numpy arrays:

1. monthly-precip-1988-to-1992.csv from https://ndownloader.figshare.com/files/12807380

2. monthly-precip-1993-to-1997.csv from https://ndownloader.figshare.com/files/12807383

Each dataset contains a row for each year specified in the dataset name and contains a column for each month (starting with January through December).

In [2]:
# set the working directory
os.chdir("/Users/markb/earth-analytics-bootcamp/")

# download monthly-precip-1988-to-1992.csv
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807380",
                          filename = "data/monthly-precip-1988-to-1992.csv")

# download monthly-precip-1993-to-1997.csv
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12807383", 
                          filename = "data/monthly-precip-1993-to-1997.csv")

# print message that files were downloaded successfully
print("Datasets sucessfully downloaded")

Datasets sucessfully downloaded


In [6]:
# import the downloaded files into new numpy arrays
precip_88_to_92 = np.loadtxt(fname = "/Users/markb/earth-analytics-bootcamp/data/monthly-precip-1988-to-1992.csv", delimiter = ",")

precip_93_to_97 = np.loadtxt(fname = "/Users/markb/earth-analytics-bootcamp/data/monthly-precip-1993-to-1997.csv", delimiter = ",")

# print message to show that files sucessfully created
print("Numpy arrays sucessfully created")

# display values in numpy array as floats rather than scientific
# notation
np.set_printoptions(suppress=True)

# print the newly created numpy arrays
print(precip_88_to_92)
print(precip_93_to_97)

Numpy arrays sucessfully created
[[0.4  1.14 2.53 1.48 3.7  0.7  0.71 1.33 2.02 0.03 0.75 2.16]
 [1.19 1.27 0.97 1.95 2.68 2.93 1.43 1.63 3.54 1.4  0.09 1.54]
 [1.04 1.32 4.55 2.16 1.73 0.39 4.23 1.13 1.84 0.96 1.6  0.75]
 [1.05 0.15 0.43 2.41 2.9  3.59 3.11 2.08 1.21 0.93 3.3  0.01]
 [0.67 0.   5.17 0.46 1.7  0.96 1.13 3.08 0.02 0.79 2.56 0.84]]
[[0.25 0.9  2.15 2.56 1.73 3.38 1.4  1.04 3.32 2.42 2.17 0.55]
 [0.86 1.37 1.61 3.46 1.35 0.93 0.35 2.56 0.54 1.02 2.25 0.49]
 [0.64 1.53 1.21 5.45 9.59 4.03 0.72 1.45 2.96 0.59 1.51 0.25]
 [1.89 0.29 2.16 1.49 4.63 2.77 1.96 0.63 3.48 0.28 1.43 0.37]
 [0.87 1.83 0.91 5.77 2.19 3.69 1.14 5.27 1.92 2.7  1.52 0.68]]
